---
- name: Copy environment file
  copy:
    src: "{{ env_file }}"
    dest: "/home/{{ ansible_user }}/{{ env_file }}"
    mode: '0644'

- name: Pull latest image
  shell: |
    docker pull {{ docker_image }}:{{ image_tag }}

- name: Deploy using Docker Compose
  shell: |
    docker compose -f {{ compose_file }} down
    docker compose -f {{ compose_file }} up -d
  args:
    chdir: /home/{{ ansible_user }}/employee-crud

- name: Verify running containers
  shell: docker ps
  register: docker_status

- debug:
    var: docker_status.stdout_lines


# Explanation:

#   Copies the .env file to the remote server.
#   Pulls the new version of the image tagged by Jenkins.
#   Brings down old containers and recreates new ones using Compose.
#   Verifies the deployment by printing running containers.













# Purpose:
#   Handles application deployment:
#   Pulls the latest Docker image.
#   Recreates the container stack using Docker Compose.
#   Ensures the application is up and running.